name=input("Enter the Name:")
branch=input("Enter the Branch:")
gender=input("Enter the Gender:")
college=input("Enter name of the college:")
age=int(input("Enter the Age:"))
print("Name:",name)
print("Branch:",branch)
print("Gender:",gender)
print("College Name:",college)
print("Age:",age)
